### ISSUE TITLE
In simulator_2/client/elev.c, could we use something "softer" than assert?

### ISSUE THREAD

**Issue by tovine** [TTK4145/Project#2]
A typical use case is to first try to initialize the elevator hardware, with a fallback to simulator if that fails (as to not have to compile two different versions or parse flags and stuff) - at least that's what I did.  
Therefore it's kind of annoying that the init function throws a fit and kills the entire application if it can't connect to the hardware...

I solved it in our case by rewriting the `elev.c` `init()` function to return `bool` instead  - replacing the `assert()` calls with `return false`.

Maybe something similar could be done for the provided example drivers as well?

**Comment by klasbo** [comment]
Yes, this is one of several reasons why `elev_init` was changed from error-return to assert:
 - People don't check error returns, and then wonder why things don't work
 - If the hardware doesn't work, there's no useful "graceful" degradation
 - Simulated hardware is not a backup plan, it's a replacement. Those are conceptually very different
 - The simulator can also fail to start, what do you do then?
 - Reading config/cmdline is a standard zero-hassle solution, where there is no implicit dependency on hardware failure

But since it seems you really want to cowboy it, I suggest `#define NDEBUG` or just `cc -DNDEBUG`.

**Comment by tovine** [comment]
Ideally I'd want an exception that could be caught and handled gracefully, unlike the `SIGABRT` that `assert()` raises. I agree that it should fail if no elevator (or simulator) is available, but being able to handle an exception gives the opportunity to do something 'nicer' (ref: [`SIGTERM` vs `SIGKILL`](http://turnoff.us/geek/dont-sigkill/))

**Comment by klasbo** [comment]
If this wasn't C (it is) and retrying `elev_init` could succeed (it can't), I would agree that exceptions are a valid approach.

But there is nothing you can (or should) do about a complete and utter initialization failure. The amount of headaches caused by unchecked return values from `elev_init` in the previous versions is too high to count, and the only correct thing that you could possibly do is just print an error message and exit. So it became an assert, and since then a lot fewer hours have been wasted on students and assistants trying to "fix" the hardware.

And if using the simulator as a fallback is a "typical use case", then it's a good thing that the asserts discourage it...
